########################
# Global Config
########################

#cache:
#    key: "$CI_RUNNER_ID"
#    paths:
#        - dl/

variables:
    CONFIG_BUILDROOT_DL_ROOT: "buildroot-ci/dl"
    GIT_STRATEGY: none

before_script:
    - export CONFIG_BUILDROOT_DL_ROOT=$HOME/$CONFIG_BUILDROOT_DL_ROOT
    - export

########################
# Job Templates
########################

# Global job template
# Used by all jobs
.global_job_template: &global_job_template
    script:
        - ./board/mathworks/common/scripts/gitlab_automation.sh
    tags: 
        - HAS_DEPLOY_CMD
    only:
        - /.*-ci$/
        - next
        - iiosdr
        - triggers
        - tags

# Deployment Jobs
.deploy_job_template: &deploy_job_template
    <<: *global_job_template
    stage: deploy

# Global sysroot template
# Used by all sysroot jobs
.sysroot_job_template: &sysroot_job_template
    <<: *global_job_template  
    stage: sysroot
    artifacts:
        paths:
            - images/$CONFIG_JOB_PLATFORM/licenses_$CONFIG_JOB_BOARD*.txt
        expire_in: 2 days

# Global setup/teardown template
# Used by all setup/teardown jobs
.setup_job_template: &setup_job_template
    <<: *global_job_template  
    script:
        - '
            if [ "$CONFIG_SETUP_SCRIPT" != "" ]; then
                $CONFIG_SETUP_SCRIPT;
            fi
        '

# Global build job template
# Used by all build jobs
.build_job_template: &build_job_template
    <<: *global_job_template  
    stage: build
    artifacts:
        paths:
            - images/$CONFIG_JOB_PROJECT/*.zip
            - images/$CONFIG_JOB_PROJECT/*.gz
        expire_in: 2 days

# Global source job template
# Used by all source jobs
.build_job_template: &source_job_template
    <<: *global_job_template  
    stage: sources_custom
    

########################
# Pipeline Definition
########################

stages:
    - setup
    - sources_common
    - build
    - sysroot
    - upload_logs
    - deploy
    - teardown

########################
# Common Jobs
########################

# Deployment Jobs
deploy_review:
    <<: *deploy_job_template
    environment:
        name: review/$CI_COMMIT_REF_NAME
        url: $CONFIG_DEPLOY_URL_ROOT/$CI_ENVIRONMENT_NAME/

deploy_staging:
    <<: *deploy_job_template
    environment:
        name: staging/$CI_COMMIT_REF_NAME
        url: $CONFIG_DEPLOY_URL_ROOT/$CI_ENVIRONMENT_NAME/
    when: manual
    only:
        - next
        - tags

# Prep and teardown jobs
setup:
    <<: *setup_job_template
    stage: setup

teardown:
    <<: *setup_job_template
    stage: teardown
    when: always

# Download the sources for all supported platforms
# Perform the download for one platform first, then copy the common bits
# To the others to save time
sources_common:
    <<: *global_job_template  
    stage: sources_common
    variables:
        GIT_STRATEGY: fetch

upload_logs:
    <<: *global_job_template
    stage: upload_logs
    when: always
    artifacts:
        paths:        
            - logs/
        expire_in: 2 weeks
    script:
        - echo "Capturing Pipeline logs"

########################
# Sysroot Jobs (per-platform)
########################

sysroot_zynq:
    <<: *sysroot_job_template
    except:
        - iiosdr
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

sysroot_socfpga:
    <<: *sysroot_job_template
    except:
        - iiosdr
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

sysroot_zynqmp:
    <<: *sysroot_job_template
    except:
        - iiosdr
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

sysroot_zynqmpsdr:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102
        CONFIG_JOB_PROJECT: apps/zynqsdr

sysroot_zynqsdr:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed
        CONFIG_JOB_PROJECT: apps/zynqsdr

########################
# Build Jobs (platform/project)
########################

build_zynq:
    <<: *build_job_template
    except:
        - iiosdr
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_PROJECT: zynq

build_socfpga:
    <<: *build_job_template
    except:
        - iiosdr
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_PROJECT: socfpga

build_zynqmp:
    <<: *build_job_template
    except:
        - iiosdr
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_PROJECT: zynqmp

build_zynqsdr:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_PROJECT: apps/zynqsdr
